name: Déploiement Yew vers GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Installation de la toolchain Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      - name: Installation de Trunk
        uses: jetli/trunk-action@v0.5.0
        with:
          version: 'latest'

      - name: Compilation Release
        # Le paramètre public-url est impératif car ton application n'est pas à la racine du domaine github.io
        run: trunk build --release --public-url /tri_pok-mon/

      - name: Upload des artefacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Déploiement effectif
        id: deployment
        uses: actions/deploy-pages@v4